"""drop report link tables

Revision ID: 0013
Revises: 0012
Create Date: 2026-09-14

Report download links are now generated by the already-deployed
scanx-pdf-proxy service instead of Command Center - that service owns its
own link storage (Firestore), 7-day expiry, and patient-facing "request a
new link" self-service page, so cc_report_links and cc_report_link_otps
(added in 0011/0012) are no longer needed.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0013"
down_revision: str | None = "0012"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.drop_index(
        "ix_cc_report_link_otps_phone",
        table_name="cc_report_link_otps",
    )
    op.drop_index(
        "ix_cc_report_link_otps_otp_id",
        table_name="cc_report_link_otps",
    )
    op.drop_table("cc_report_link_otps")

    op.drop_index(
        "ix_cc_report_links_token",
        table_name="cc_report_links",
    )
    op.drop_index(
        "ix_cc_report_links_appointment_id",
        table_name="cc_report_links",
    )
    op.drop_table("cc_report_links")


def downgrade() -> None:
    op.create_table(
        "cc_report_links",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("appointment_id", sa.String(length=64), nullable=False),
        sa.Column("token", sa.String(length=64), nullable=False),
        sa.Column("gcs_blob_name", sa.String(length=512), nullable=False),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("accessed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_cc_report_links_appointment_id",
        "cc_report_links",
        ["appointment_id"],
        unique=False,
    )
    op.create_index(
        "ix_cc_report_links_token",
        "cc_report_links",
        ["token"],
        unique=True,
    )

    op.create_table(
        "cc_report_link_otps",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("otp_id", sa.String(length=64), nullable=False),
        sa.Column("phone", sa.String(length=32), nullable=False),
        sa.Column("code_hash", sa.String(length=64), nullable=False),
        sa.Column("appointment_id", sa.String(length=64), nullable=False),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_cc_report_link_otps_otp_id",
        "cc_report_link_otps",
        ["otp_id"],
        unique=True,
    )
    op.create_index(
        "ix_cc_report_link_otps_phone",
        "cc_report_link_otps",
        ["phone"],
        unique=False,
    )
